# Generated by Django 2.2 on 2019-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('employee_id', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=200)),
                ('c_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
