# Generated by Django 2.2 on 2019-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='exp_otp',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='login_otp',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
