# Generated by Django 2.2 on 2019-04-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190419_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='c_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
