# Generated by Django 2.2 on 2019-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190419_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
