# Generated by Django 2.2 on 2019-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_login_time', models.DateTimeField(null=True)),
                ('employee_logout_time', models.DateTimeField(null=True)),
                ('employee_break_in_time', models.CharField(max_length=255, null=True)),
                ('employee_break_out_time', models.CharField(max_length=255, null=True)),
                ('employee_extra_time', models.CharField(max_length=100, null=True)),
                ('current_day', models.CharField(max_length=200, null=True)),
                ('current_date', models.DateTimeField(auto_now=True, null=True)),
                ('break_reason', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
