# Generated by Django 2.2 on 2019-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeetimings', '0002_auto_20190424_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='employee_email',
            field=models.EmailField(max_length=254),
        ),
    ]
