# Generated by Django 2.2 on 2019-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeetimings', '0003_auto_20190424_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='current_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeetime',
            name='employee_login_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeetime',
            name='employee_logout_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
