# Generated by Django 2.2 on 2019-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
